export const formattedModules = {
        autoP3: "Auto P3",
        autoClear: "Auto Clear",
        autoBoss: "Auto Boss",
    },
    misc: {
        autoBless: "Auto Bless",
        autoRequeue: "Auto Requeue",
        chatCleaner: "Chat Cleaner",
        maskTimer: "Mask Timer",
        mobHighlight: "Mob Highlight",
        relicUtils: "Relic Utils",
        sheepHider: "Sheep Hider",
    },
    termsInfo: {
        movementTimer: "Movement Timer",
        positionalAlerts: "Positional Alerts",
        sectionTimes: "Section Times",
        termInfo: "Term Info",
        termTimes: "Term Times",
    },
    splits: {
        padTimers: "Pad Timers",
        pdSplits: "PreDev Splits",
        splits: "Splits",
        subSplits: "Sub Splits",
    },
    autoClear: {
        autoMap: "Auto Map",
        auto0s: "Auto 0s",
        autoCamp: "Auto Camp",
        autoPuzzles: "Auto Puzzles",
        autoRoutes: "Auto Routes",
    },
    autoBoss: {
        autoTerms: "Auto Terms",
        p3routes: "P3 Routes",
        preTerms: "Pre Terms",
        postTerms: "Post Terms",
        p5: "P5",
    },
}
